### ISSUE TITLE
Incomplete data imported

### ISSUE THREAD

**Issue by mtleung** [pgRouting/osm2pgrouting#114]
Originally posted on http://gis.stackexchange.com/questions/159842/incomplete-data-lines-missing-from-osm2pgrouting

I am importing OSM data into PostGIS using the latest version of osm2pgrouting but some data is missing/did not import. I am using the default mapconfig.xml and this appears to work for most roads.
Running on:
PostGIS version 2.1.7
PostgreSQL version 9.4.4
Ubuntu 14.04

For example in below screencap, blue is the ways created by osm2pgrouting, and red is the line when the data is imported using osm2pgsql (using default.style and red filtered on "highway" = 'motorway' for this questions purposes). The missing section is a bridge, however other bridges have imported correctly, and some other roads (like 'service') are also missing.

![missing_line](https://cloud.githubusercontent.com/assets/6822353/9538692/b3306b3a-4d79-11e5-93ce-c85a480f3015.png)

The osm id of one of the missing lines in the pic is 158307203 if that helps, data sourced from Mapzen. The line has this tag so I am not sure why it is not being imported.

Below is the log when I imported the data:
```
$osm2pgrouting -file ~/osm2pgrouting/mapconfig.xml -dbname gis -user gisuser -passwd gisuser -clean
host=127.0.0.1 user=gisuser dbname=gis port=5432 password=gisuser
connection success
Trying to load config file /path/to/mapconfig.xml
Trying to parse config
Trying to load data
Trying to parse data
unknown maxspeed value: 56; 72; 72
unknown maxspeed value: 56;108
unknown maxspeed value: 56;108
Split ways
Dropping tables...
Creating tables...
Nodes table created
2create ways failed:
Types table created
Way_tag table created
Relations table created
Relation_ways t
![missing_line](https://cloud.githubusercontent.com/assets/6822353/9538688/aac4f678-4d79-11e5-8bdd-9fecd863b323.png)
able created
Classes table created
Adding tag types and classes to database...
Adding relations to database...
Adding nodes to database...
Adding ways to database...
Creating topology...
NOTICE:  PROCESSING:
NOTICE:  pgr_createTopology('ways',1e-05,'the_geom','gid','source','target','tru
NOTICE:  Performing checks, pelase wait .....
NOTICE:  Creating Topology, Please wait...
NOTICE:  1000 edges processed
...
NOTICE:  282000 edges processed
NOTICE:  -------------> TOPOLOGY CREATED FOR  282284 edges
NOTICE:  Rows with NULL geometry or NULL id: 0
NOTICE:  Vertices table for table osm2pgr.ways is: osm2pgr.ways_vertices_pgr
NOTICE:  ----------------------------------------------
Create Topology success
```
I noticed the "2create ways failed" message but not sure why no error message was generated.

**Comment by cvvergara** [comment]
Hi marco, we are in the middle of changing a bit osm2pgrouting,
if you clone the repository and try with-schema branch
and see how that does, it would be nice.

**Comment by mtleung** [comment]
Hi Vicky, I just tried it and the same line is missing.
The count of the ways from the master branch and the with-schema branch is also the same.

**Comment by cvvergara** [comment]
Marco, 
Can you give me the osm bounding box of the data you are loading?
Also the osm id of the bridge.
I need to reproduce the error.

**Comment by mtleung** [comment]
Hi Vicky, I just tried it with a raw osm export for a small section and a larger section via the Overpass API.... and they both worked. So I guess its a problem with Mapzen. Issue considered resolved?

**Comment by cvvergara** [comment]
Yes, its resolved then.
