### ISSUE TITLE
Can't compile under mingw64 anymore

### ISSUE THREAD

**Issue by robe2** [pgRouting/osm2pgrouting#123]
Did something change in compilation between the 2.1.0-alpha and 2.1.0-beta releases.

Getting compile error when trying to compile 2.1.0-beta -  http://winnie.postgis.net:1500/job/osm2pgRouting_PGVersionEDB/33/console

> e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp: In function 'int main(int, char**)':
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:47:13: error: 'cout' is not a member of 'std'
             std::cout << od_desc << "\n";
             ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:52:13: error: 'cout' is not a member of 'std'
             std::cout << "This is osm2pgrouting Version 2.1 beta\n";
             ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:61:13: error: 'cout' is not a member of 'std'
             std::cout << ex.what() << "\n";
             ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:62:13: error: 'cout' is not a member of 'std'
             std::cout << od_desc << "\n";
             ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:66:9: error: 'cout' is not a member of 'std'
         std::cout << "Execution starts at: " << std::ctime(&start_t) << "\n";
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:75:9: error: 'cout' is not a member of 'std'
         std::cout << "Connecting to the database"  << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:80:17: error: 'cout' is not a member of 'std'
                 std::cout << "ERROR: postGIS not found\n";
                 ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:85:9: error: 'cout' is not a member of 'std'
         std::cout << "Opening configuration file: " << confFile.c_str() << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:90:9: error: 'cout' is not a member of 'std'
         std::cout << "    Parsing configuration\n" << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:94:17: error: 'cout' was not declared in this scope
                 cout << "Failed to open / parse config file " << confFile.c_str() << endl;
                 ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:99:9: error: 'cout' is not a member of 'std'
         std::cout << "Opening data file: " << dataFile.c_str() << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:103:9: error: 'cout' is not a member of 'std'
         std::cout << "    Parsing data\n" << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:106:13: error: 'cerr' was not declared in this scope
             cerr << "Failed to open / parse data file " << dataFile.c_str() << endl;
             ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:110:9: error: 'cout' is not a member of 'std'
         std::cout << "Spliting ways\n" << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:116:13: error: 'cout' is not a member of 'std'
             std::cout << "Dropping tables..." << endl;
             ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:120:9: error: 'cout' is not a member of 'std'
         std::cout << "Creating tables..." << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:123:9: error: 'cout' is not a member of 'std'
         std::cout << "Adding auxiliary tables to database..." << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:135:13: error: 'cout' is not a member of 'std'
             std::cout << "Creating topology..." << endl;
             ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:140:9: error: 'cout' is not a member of 'std'
         std::cout << "#########################" << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:142:9: error: 'cout' is not a member of 'std'
         std::cout << "size of streets: " << document->m_Ways.size() <<    endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:143:9: error: 'cout' is not a member of 'std'
         std::cout << "size of splitted ways : " << document->m_SplittedWays.size() <<    endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:154:9: error: 'cout' is not a member of 'std'
         std::cout << "Execution started at: " << std::ctime(&start_t);
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:155:9: error: 'cout' is not a member of 'std'
         std::cout << "Execution ended at:   " << std::ctime(&end_t);
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:156:9: error: 'cout' is not a member of 'std'
         std::cout << "Elapsed time: " << (double)duration.count()/(double)1000 << " Seconds.\n" ;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:157:9: error: 'cout' is not a member of 'std'
         std::cout << "User CPU time: -> " << elapsed_secs << " seconds\n";
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:159:9: error: 'cout' is not a member of 'std'
         std::cout << "#########################" << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:165:9: error: 'cout' is not a member of 'std'
         std::cout << e.what() << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:169:9: error: 'cout' is not a member of 'std'
         std::cout << e << endl;
         ^
e:/jenkins/osm2pgrouting/branches/2.1.0-beta/src/osm2pgrouting.cpp:173:9: error: 'cout' is not a member of 'std'
         std::cout << "Terminating" << endl;
         ^
CMakeFiles/osm2pgrouting.dir/build.make:205: recipe for target `CMakeFiles/osm2pgrouting.dir/src/osm2pgrouting.cpp.obj' failed
make[2]: *** [CMakeFiles/osm2pgrouting.dir/src/osm2pgrouting.cpp.obj] Error 1
make[2]: Leaving directory `/projects/osm2pgrouting/build64gcc48'
CMakeFiles/Makefile2:66: recipe for target `CMakeFiles/osm2pgrouting.dir/all' failed
make[1]: *** [CMakeFiles/osm2pgrouting.dir/all] Error 2
make[1]: Leaving directory `/projects/osm2pgrouting/build64gcc48'
Makefile:119: recipe for target `all' failed
make: *** [all] Error 2

**Comment by robe2** [comment]
@cvvergara  fixed in develop

**Comment by cvvergara** [comment]
in Tag 2.1.0-RC1
