### ISSUE TITLE
Keep the class with the lowest priority

### ISSUE THREAD

**Issue by PanierAvide** [pgRouting/osm2pgrouting#130]
Hello,
Currently, OSMDocumentParserCallback analyzes each tag from XML in reading order, and changes way type and class when they exist in configuration file. I'm working on bicycle routing, and when OSM XML is read, highway tag comes after cycleway tag. Even with priorities set in configuration, the cycleway class is overwritten by the last found, the highway one.
So I think it may be better to keep the class with the lowest priority, instead of the last found one. I created a quick patch to change this.

OSMDocumentParserCallback.cpp
```
               // else if (m_pActWay && k.compare("highway") == 0)
                else if (m_pActWay && m_rDocument.m_rConfig.m_Types.count(k)) {
					if(
						(m_pActWay->type.compare("") == 0 && m_pActWay->clss.compare("") == 0)
						|| (
							m_rDocument.m_rConfig.m_Types.count(k)
							&& m_rDocument.m_rConfig.m_Types[k]->m_Classes.count(v)
							&& m_rDocument.m_rConfig.m_Types.count(m_pActWay->type)
							&& m_rDocument.m_rConfig.m_Types[m_pActWay->type]->m_Classes.count(m_pActWay->clss)
							&& m_rDocument.m_rConfig.m_Types[k]->m_Classes[v]->priority < m_rDocument.m_rConfig.m_Types[m_pActWay->type]->m_Classes[m_pActWay->clss]->priority
						)
					) {
						m_pActWay->type = k;
						m_pActWay->clss = v;

						if (m_rDocument.m_rConfig.m_Types.count(m_pActWay->type) && m_rDocument.m_rConfig.m_Types[m_pActWay->type]->m_Classes.count(m_pActWay->clss)) {
							m_pActWay->AddTag(k, v);

							// std::cout<<"Added tag: "<<k<<" "<<v<<std::endl;

							// set default maxspeed values from classes, if not set previously (default: -1)
							if (m_pActWay->maxspeed_forward <= 0) {
								int newValue = m_rDocument.m_rConfig.m_Types[m_pActWay->type]->m_Classes[m_pActWay->clss]->default_maxspeed;
								m_pActWay->maxspeed_forward = newValue;
							}
							if (m_pActWay->maxspeed_backward <= 0) {
								int newValue = m_rDocument.m_rConfig.m_Types[m_pActWay->type]->m_Classes[m_pActWay->clss]->default_maxspeed;
								m_pActWay->maxspeed_backward = newValue;
							}
						}
					}
                }
```

The mapconfig.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <type name="cycleway" id="1">
    <class name="track" priority="1.0" id="101" />
    <class name="lane" priority="1.5" id="102" />
    <class name="opposite_lane" priority="1.5" id="103" />
    <class name="opposite" priority="1.5" id="104" />
    <class name="shared_lane" priority="1.6" id="105" />
    <class name="shared" priority="1.6" id="106" />
    <class name="share_busway" priority="1.6" id="107" />
  </type>
  <type name="cycleway:right" id="2">
    <class name="track" priority="1.0" id="201" />
    <class name="lane" priority="1.5" id="202" />
    <class name="opposite_lane" priority="1.5" id="203" />
    <class name="opposite" priority="1.5" id="204" />
    <class name="shared_lane" priority="1.6" id="205" />
    <class name="shared" priority="1.6" id="206" />
    <class name="share_busway" priority="1.6" id="207" />
  </type>
  <type name="cycleway:left" id="3">
    <class name="track" priority="1.0" id="301" />
    <class name="lane" priority="1.5" id="302" />
    <class name="opposite_lane" priority="1.5" id="303" />
    <class name="opposite" priority="1.5" id="304" />
    <class name="shared_lane" priority="1.6" id="305" />
    <class name="shared" priority="1.6" id="306" />
    <class name="share_busway" priority="1.6" id="307" />
  </type>
  <type name="tracktype" id="4">
    <class name="grade1" priority="1.0" id="401" />
    <class name="grade2" priority="1.1" id="402" />
    <class name="grade3" priority="1.2" id="403" />
    <class name="grade4" priority="1.3" id="404" />
    <class name="grade5" priority="1.4" id="405" />
  </type>
  <type name="highway" id="5">
    <class name="cycleway" priority="1.0" id="501" />
    <class name="path" priority="1.1" id="502" />
    <class name="pedestrian" priority="1.1" id="503" />
    <class name="footway" priority="1.1" id="504" />
    <class name="bridleway" priority="1.3" id="505" />
    <class name="track" priority="1.0" id="506" />
    <class name="living_street" priority="2.0" id="507" />
    <class name="service" priority="2.0" id="508" />
    <class name="residential" priority="2.2" id="509" />
    <class name="unclassified" priority="2.3" id="510" />
    <class name="tertiary_link" priority="2.5" id="511" />
    <class name="tertiary" priority="2.5" id="512" />
    <class name="services" priority="2.7" id="513" />
    <class name="secondary_link" priority="3.0" id="514" />
    <class name="secondary" priority="3.0" id="515" />
    <class name="primary_link" priority="3.5" id="516" />
    <class name="primary" priority="3.5" id="517" />
    <class name="road" priority="4.0" id="500" />
  </type>
  <type name="junction" id="6">
    <class name="roundabout" priority="2.5" id="601" />
  </type>  
</configuration>
```

**Comment by cvvergara** [comment]
@PanierAvide 
I guess you made the change in your fork, I would like to incorporate your change into develop branch. (cant into master because its not a release)

This is important:
how much does the result changes for the car's output. compared to what is the current code?.

# For making a pull request:

Suppose you made the change on master on yuour fork but didn't commit your code
Commit the code:
```
git commit -a -m 'Added improvement issue #130'
```

After the code is commited, branch out, push & go back to develop:
```
git checkout -b improvement/issue130
git push --set-upstream origin  improvement/issue130
git checkout develop
```

And from the web page, please make the pull request

After I merge:
```
git fetch upstream
```

**Comment by PanierAvide** [comment]
I created the pull request. I made a comparison of results, see below.

With mapconfig.xml, before patch
```
testpgr=# select class_id, count(*) from ways group by class_id order by class_id;
 class_id | count 
----------+-------
      109 |    41
      110 |     6
      112 |     9
      113 |     6
      117 |    16
      123 |    94
      301 |     1
      302 |    10
      303 |    33
      304 |     7
      305 |     7
(11 lignes)
```

With mapconfig.xml, after patch
```
testpgr2=# select class_id, count(*) from ways group by class_id order by class_id;
 class_id | count 
----------+-------
      109 |    41
      110 |     6
      112 |     9
      113 |    64
      117 |    16
      123 |    94
(6 lignes)
```

The difference is explained by the selected area, having a few `highway=track + tracktype=*`. Before, tracktype class overwrites the highway one. After patch, it doesn't as in mapconfig.xml they have the same priority. This behaviour can be changed by setting `<=` operator instead of `<` in the priority condition.

With mapconfig_for_cars.xml, before patch
```
testpgr=# select class_id, count(*) from ways group by class_id order by class_id;
 class_id | count 
----------+-------
      110 |    41
      112 |     6
      114 |     9
      117 |    94
(4 lignes)
```

With mapconfig_for_cars.xml, after patch
```
testpgr2=# select class_id, count(*) from ways group by class_id order by class_id;
 class_id | count 
----------+-------
      110 |    41
      112 |     6
      114 |     9
      117 |    94
(4 lignes)
```

No changes for cars, as only `highway=*` tag is considered.

**Comment by cvvergara** [comment]
what happened to this, I didnt understand your explanation
```
     301 |     1
      302 |    10
      303 |    33
      304 |     7
      305 |     7
(11 lignes)
```

**Comment by PanierAvide** [comment]
In the given area, there are several ways in OSM having `highway=track + tracktype=*` tags. In mapconfig.xml, there are classes for highway=track and tracktype=*. No priority attribute is defined in mapconfig.xml, so every class has the same priority. When OSMDocumentParserCallback processes the input OSM file, it reads first the tag `highway`, then the `tracktype` one.
Before the patch, reading the `tracktype` tag edits the type and class of the Way object. It overwrites the previously read type and class, defined when tag `highway` was processed. So ways with class 301 to 305 appears in results.
After the patch, same process, OSMDocumentParserCallback reads first tag `highway`, and defines type and class on Way object. But when it reads tag `tracktype`, as no priority is defined, tracktype classes haven't a lower priority than highway classes. So the new condition isn't met, type and class of current Way object aren't overwritten. So these ways keep the highway classes, that's why there are 58 more ways in class 113.

**Comment by cvvergara** [comment]
@PanierAvide  
The mapconfig.xml that you posted in the [https://github.com/pgRouting/osm2pgrouting/issues/130#issue-151338399] looks different from the "basic" [mapconfig.xml](https://github.com/pgRouting/osm2pgrouting/blob/master/mapconfig.xml)
So why don't you add the posted mapconfig.xml  in the comment as:
cycle_mapconfig.xml
I am sure people will find it useful.

I might say that you tested the code/cycle_mapconfig.xml combination, but:
What happens when that code is used with the original basic mapconfig.xml? does it work the same as without the code you wrote?

**Comment by cvvergara** [comment]
oh, I see. looks reasonable

**Comment by PanierAvide** [comment]
The tests were made with the original mapconfig.xml and mapconfig_for_cars.xml given in osm2pgrouting. With the cycle_mapconfig.xml, when a secondary road has a cycleway lane (tags `highway=secondary + cycleway=lane` for example), the way in DB has the cycleway=lane class (102) instead of the highway=secondary class (515), because cycleway class has a lower priority value.
I can add the given cycle_mapconfig.xml in the improvement/issue130 branch and create another pull request.

**Comment by cvvergara** [comment]
add it, & push I think it updates the pull request

**Comment by PanierAvide** [comment]
Apparently it does, the commit is listed in the pull request.

**Comment by cvvergara** [comment]
@PanierAvide Merged, closing this issue, thanks very much!!!!

**Comment by cvvergara** [comment]
@PanierAvide 
I made a code rewrite, its merged in develop, its for the 2.2 release of osm2pgRouting.

In theory I don't brake anything, but I was wondering if you have time to test the the mapconfig_for bicycles
and see if everything looks to be all right?
I already tested the other 2, and started working on a "pedestrian" (but I am not going to include the pedestrian in 2.2 version)

**Comment by PanierAvide** [comment]
I can't test, import isn't working:
```
[adrien@pc-portable build]$ osm2pgrouting --f /tmp/data.osm --conf /usr/share/osm2pgrouting/mapconfig_for_bicycles.xml --dbname testo2pgr --username postgres --clean
Execution starts at: Wed Oct 19 15:57:00 2016

***************************************************
           COMMAND LINE CONFIGURATION             *
***************************************************
Filename = /tmp/data.osm
Configuration file = /usr/share/osm2pgrouting/mapconfig_for_bicycles.xml
host = localhost
port = 5432
dbname = testo2pgr
username = postgres
password = 
schema= 
prefix = 
suffix = 
Drop tables
Don't add nodes
***************************************************
Connecting to the database
host=localhost user=postgres dbname=testo2pgr port=5432
connection success
Opening configuration file: /usr/share/osm2pgrouting/mapconfig_for_bicycles.xml
    Parsing configuration

Opening data file: /tmp/data.osm total lines 28248
    Parsing data

bad lexical cast: source type value could not be interpreted as target
```
Running under Arch Linux 64bits, having:
* postgresql 9.5.4-1
* postgis 2.2.2-1
* pgrouting 2.2.3-2
* boost 1.61.0-2
* expat 2.2.0-2
* cmake 3.6.2-1

**Comment by cvvergara** [comment]
@PanierAvide 
Can you send me (or how to get it) the .osm file because I don't get the error
with my test files

**Comment by PanierAvide** [comment]
Here it is, it's a small part of Rennes, France: https://framadrop.org/r/bMvwWzXlD_#okSFHMGVC3S96IiiFQV6ndjQrQVchs42vkhzxMjFTUI=

**Comment by cvvergara** [comment]
Reading around, I want to make sure that I use exactly the data you have,
just to discard that the data is "corrupted".
 can you send me your file?

**Comment by PanierAvide** [comment]
I sent you the exact file I used. I will try downloading another area to test if it does the same.

**Comment by cvvergara** [comment]
or is that your file?

**Comment by cvvergara** [comment]
I get that error, I'll inspect where its happening

**Comment by PanierAvide** [comment]
It happens also with another file over another area I downloaded in Rennes with JOSM, see: https://framadrop.org/r/Xjv0ixBY74#/CKzvvZkxt8qUWJGe7inioUMakYi3l8IVZ6+NnZMfqY=

**Comment by cvvergara** [comment]
found the error, 
FYI
the files I have don't have the visible attribute, and I miss handled it.

I pushed again can you test to confirm that its working?

**Comment by cvvergara** [comment]
btw what is your name (so I can add you as contributor in contributors iist)

**Comment by PanierAvide** [comment]
It's working as expected, thank you for your correction. My name is Adrien Pavie, thanks for adding me to the contributors list :-)

**Comment by cvvergara** [comment]
@PanierAvide 
Do you have a tweeter account?

**Comment by PanierAvide** [comment]
Yes, here: https://twitter.com/PanierAvide
