### ISSUE TITLE
Debugging (while implementing a way to add version & timestamp of OSM objects)

### ISSUE THREAD

**Issue by aakashysharma** [pgRouting/osm2pgrouting#137]
I am trying to modify osm2pgrouting to extract version & timestamp of osm objects such as nodes & ways, while maintaining the possibility of routing. The fork is available here https://github.com/aakashysharma/osm2pgrouting

So far, I've been able to modify & import version & timestamp for nodes. However, attempting to extract & import other objects (way, relation) have left me with blank tables after import.

A recent import displayed this message
```
Adding auxiliary tables to database...
    Processing 4371841 nodes:  Inserted: 4371841
    Processing 1 way types:  Inserted 1 way types
    Processing way's classes:  Inserted 16 way's classes
    Processing way's relations:  Inserted: 223030way's relations
    Processing way's tags:  Inserted 144851 way's tags
    Processing 144851 ways:
Vertices inserted 91046    Ways inserted: 100000
Vertices inserted 29565    Ways inserted: 144851

```

It's clear somewhere I've screwed up while attempting to import way into db. The extraction from xml file works however while importing, I get this without any error.

I was wondering if you could provide some pointers or a way to debug this issue.
Thanks a lot in advance.

**Comment by cvvergara** [comment]
@aakashysharma 
known bug: relations table comes out empty, so we are the same here
I would not know why "ways" table is comming empty in your changes

I created the branch with-timestamps, if you make the pull request to that branch I can try to give you a hand.
https://github.com/pgRouting/osm2pgrouting/compare/with-timestamp...aakashysharma:master

**Comment by aakashysharma** [comment]
I did. In my (current) version, ways are coming out fine however I've commented out code which was attempt to add version & timestamp while importing into db.

**Comment by cvvergara** [comment]
Yes noticed that you commented what was not working for example
https://github.com/pgRouting/osm2pgrouting/pull/138/files#r76533690
So first step is coordinate each other with testing. Right now I am compiling and testing. 
See https://github.com/pgRouting/osm2pgrouting/issues/44#issuecomment-105068908
to test with the same data (might be slightly different from mine because I made the download long ago)


Some results I get:
```
SELECT count(*) FROM ways;
 count  
--------
 110029
(1 row)


\dS osm_nodes;
                                       Table "public.osm_nodes"
  Column   |            Type             |                          Modifiers                          
-----------+-----------------------------+-------------------------------------------------------------
 node_id   | bigint                      | not null default nextval('osm_nodes_node_id_seq'::regclass)
 osm_id    | bigint                      | 
 lon       | numeric(11,8)               | 
 lat       | numeric(11,8)               | 
 numofuse  | integer                     | 
 version   | integer                     | 
 timestamp | timestamp without time zone | 
 the_geom  | geometry(Point,4326)        | 
Indexes:
    "osm_nodes_pkey" PRIMARY KEY, btree (node_id)
    "node_id" UNIQUE CONSTRAINT, btree (osm_id)


SELECT count(*) FROM osm_nodes;
  count  
---------
 2551588
(1 row)

SELECT numofuse, version, timestamp
FROM osm_nodes WHERE osm_id = 27196027;
 numofuse | version |      timestamp      
----------+---------+---------------------
        1 |       6 | 2015-03-25 03:22:33
(1 row)
```

**Comment by aakashysharma** [comment]
I couldn't download through the method written in #44 but I downloaded () through alternative url using same BBOX parameters. 

At my end after importing, it looks like this
```
SELECT count(*) FROM ways;
 count  
--------
 120513
(1 row)

                                                           Table "public.osm_nodes"
  Column   |            Type             |                          Modifiers                          | Storage | Stats target | Description 
-----------+-----------------------------+-------------------------------------------------------------+---------+--------------+-------------
 node_id   | bigint                      | not null default nextval('osm_nodes_node_id_seq'::regclass) | plain   |              | 
 osm_id    | bigint                      |                                                             | plain   |              | 
 lon       | numeric(11,8)               |                                                             | main    |              | 
 lat       | numeric(11,8)               |                                                             | main    |              | 
 numofuse  | integer                     |                                                             | plain   |              | 
 version   | integer                     |                                                             | plain   |              | 
 timestamp | timestamp without time zone |                                                             | plain   |              | 
 the_geom  | geometry(Point,4326)        |                                                             | main    |              | 
Indexes:
    "osm_nodes_pkey" PRIMARY KEY, btree (node_id)
    "node_id" UNIQUE CONSTRAINT, btree (osm_id)
Has OIDs: no


SELECT count(*) FROM osm_nodes;
  count  
---------
2642285
(1 row)


SELECT numofuse, version, timestamp
FROM osm_nodes WHERE osm_id = 27196027;
 numofuse | version |      timestamp      
----------+---------+---------------------
        1 |       6 | 2015-03-25 03:22:33
```

**Comment by cvvergara** [comment]
@aakashysharma 
Now that we are coordinated.
You will be uncommenting  little by little
ok, so osrm_nodes is ok, so now only focus on one table, (choose which one, "think easy") and uncomment just for that one, do a similar test and post the test on a pull request with the changes.

**Comment by cvvergara** [comment]
@aakashysharma 
I posted a comment on your latest pull request

**Comment by aakashysharma** [comment]
Thanks so much for your assistance @cvvergara . I've fixed now for import for timestamp as well for ways. I also created pull request #140 

As you said earlier, osm_relation comes out empty but I can live with that for now.

**Comment by cvvergara** [comment]
@aakashysharma glad to be of help, and thanks for the pull request.
