### ISSUE TITLE
Finding it impossible to import ways

### ISSUE THREAD

**Issue by markjd84** [pgRouting/osm2pgrouting#150]
Have used the tool in the past with some success, but have just had to reinstall it on a new machine. Tried installing various versions of the tool but none of them seem to produce any actual routable ways, despite various configs and trying data from different sources. I'm getting my data from Mapzen (which I understand in the past may have caused trouble) but have also tried PBFs converted to xml from conveyal's [osm-lib](https://github.com/conveyal/osm-lib).

```
production=> select count(*) from osm2pgrways_vertices_pgr;
 count
--------
 227986
(1 row)

production=> select count(*) from osm2pgrways;
 count
-------
     0
(1 row)
```

The above is from trying to load Mapzen's export of [Brussels](https://mapzen.com/data/metro-extracts/metro/brussels_belgium/), using the command line per the readme with `--clean`. Is there something I'm doing wrong, or should I be getting the data from elsewhere? Any help or advice anyone can give is much appreciated!

PostgreSQL 9.3.14
PostGIS 2.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
pgRouting 2.3.0
osm2pgrouting-2.1~develop
libboost-all-dev 1.54.0.1ubuntu1
cmake 2.8.12.2-0ubuntu3
libexpat1-dev 2.1.0-4ubuntu1.3

**Comment by cvvergara** [comment]
Using https://github.com/pgRouting/osm2pgrouting/tree/develop

I tried with this section of brussels
```
BBOX="4.2878,50.8139,4.5023,50.8926"
wget --progress=dot:mega -O "brussels.osm" "http://www.overpass-api.de/api/xapi?*[bbox=${BBOX}][@meta]"
```

Preparing the db
```
dropdb --if-exists brussels
createdb brussels
psql -c "CREATE EXTENSION postgis" --dbname brussels
psql -c "CREATE EXTENSION pgrouting" --dbname brussels

osm2pgrouting \
    -c ./mapconfig_for_cars.xml \
    -f brussels.osm \
    --dbname brussels \
    -U zzzz \
    -W xxxx
```

And visually ran a query using qgis

![brussels](https://cloud.githubusercontent.com/assets/5035290/19691052/76db6276-9a98-11e6-99ca-a6c1779a9df4.png)

**Comment by markjd84** [comment]
Ok thanks 

I think the problems I was having may relate to using the `--prefix` option. Following your exact example worked fine (I was always using the `develop` branch) but still in my own code it didn't work. I then noticed the error message below (which I don't know if I'd seen before), about not being able to access a specific table. Anyway on a hunch I removed `--prefix` and now my `ways` table is populated. 

Also, thanks for info re. using Overpass, I've never properly got my head around doing simple extracts like that and it's way more flexible than using Mapzen. 

Cheers!

```
Export Types ...
    Processing 1 way types:      Inserted: 0 in osm_way_types

Export Classes ...
    Processing way's classes:    Inserted: 0 in osm_way_classes

Export Relations ...
    Processing 0 relations:7Inserting to osm_relations failed
ERROR:  relation "osm2pgrosm_relations" does not exist
LINE 1: ... ( SELECT a.*  FROM  __relations_temp a LEFT JOIN osm2pgrosm...
                                                             ^


Export RelationsWays ...
    Processing way's relations:          Inserted: 0 in osm2pgrrelations_ways
```
