### ISSUE TITLE
after importing without --clean option duplicate foreign keys created

### ISSUE THREAD

**Issue by slbug** [pgRouting/osm2pgrouting#159]
<pre>
Foreign-key constraints:
    "osm_way_classes_type_id_fkey" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
    "osm_way_classes_type_id_fkey1" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
    "osm_way_classes_type_id_fkey2" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
    "osm_way_classes_type_id_fkey3" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
    "osm_way_classes_type_id_fkey4" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
    "osm_way_classes_type_id_fkey5" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
    "osm_way_classes_type_id_fkey6" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
    "osm_way_classes_type_id_fkey7" FOREIGN KEY (type_id) REFERENCES osm_way_types(type_id)
</pre>

May be foreign keys should be created only on clean import or check if constraint exists before creating it

**Comment by cvvergara** [comment]
Will do it only on the clean import. for the 2.2.1

**Comment by slbug** [comment]
also i have a question, is there a possibility to import new diff file? (e.g. delete some nodes, create new ones, etc). just to have routing DB synced to current OSM DB. and sync should not not take a lot of time.

**Comment by cvvergara** [comment]
never tried it, but, it will use the incremental update,  new things get added but not deleted.
