### ISSUE TITLE
What is "boost"

### ISSUE THREAD

**Issue by Stophface** [pgRouting/osm2pgrouting#161]
One of the requirements to install osm2pgrouting is "boost". That name is a little to generic for googling it. What software/framework/... is it?

**Comment by cvvergara** [comment]
@Stophface 
This is boost:
http://www.boost.org/
in particular it uses this one
http://www.boost.org/doc/libs/1_62_0/doc/html/program_options.html
which is a header only library.

**Comment by Stophface** [comment]
@cvvergara thanks a lot!
