### ISSUE TITLE
Parsing data not well-formed (invalid token)

### ISSUE THREAD

**Issue by zolden** [pgRouting/osm2pgrouting#166]
Hi, I try importing osm data into postgis and I get this issues 
_Parsing data (progress line per 100000 elements)
not well-formed (invalid token) at line 1    Finish Parsing data_

full console print is described here:
http://stackoverflow.com/questions/41770302/osm2pgrouting-parsing-data-not-well-formed-invalid-token

**Comment by cvvergara** [comment]
From the console print, the configuration file is read, the data file is not read.
Data from Mapzen is not good for osm2pgrouting.
How do you get the data?

**Comment by zolden** [comment]
I solve it with convert osm.pbf to osm file
