### ISSUE TITLE
Cannot Open Error

### ISSUE THREAD

**Issue by masgeomatik** [pgRouting/osm2pgrouting#178]
Hi. I try this code:
`file http://routingo.com/veriler/andorra.osm conf mapconfig.xml dbname postgres username postgres`
dbname, username and web adress is correct.
But give an error.
![error](https://user-images.githubusercontent.com/26778438/29496013-892170a8-85d2-11e7-96f0-7fdf1cc453aa.PNG)

How can I fix it?

**Comment by smellman** [comment]
Why do you run `file` command?
All errors are from `file` command, it is not `osm2pgrouting` command.

First, you need to download osm file.

```
wget http://routingo.com/veriler/andorra.osm
```

And you run `osm2pgrouting` command.

```
osm2pgrouting --f andorra.osm --conf mapconfig.xml --dbname postgres --username postgres
```

Please read (README.md)[https://github.com/pgRouting/osm2pgrouting/blob/master/Readme.md] file carefully, and you may need to learn about command line.

**Comment by masgeomatik** [comment]
![errror3](https://user-images.githubusercontent.com/26778438/29533763-0c9f8390-86bc-11e7-86cb-fc5079068182.PNG)
No command error. (komut yok)

**Comment by dkastl** [comment]
@masgeomatik does it work for you now?

**Comment by woodbri** [comment]
``-bash: osm2pgrouting: komut yok`` means that bash could not find the osm2pgrouting command in the path. This suggests that you have not installed osm2pgrouting on your system.

You need to install this first. What OS, distribution are you running. On Ubuntu, try running ``sudo apt-get install osm2pgrouting``

**Comment by dkastl** [comment]
@masgeomatik , please do not post your questions on multiple locations without adding a reference.

Closing this as the issues is discussed here already: 
https://gis.stackexchange.com/questions/252659/cannot-open-error-pgrouting
