### ISSUE TITLE
'wc' is not recognized as an internal or external command, on windows

### ISSUE THREAD

**Issue by robe2** [pgRouting/osm2pgrouting#191]
I compiled osm2pgrouting 2.3.1 under mingw64 for postgis bundle distribution.

When I run load I get this:

> host = localhost
port = 5447
dbname = test_db
username = postgres
password =
schema=
prefix =
suffix =
Install postgis if not found
Drop tables
Don't create indexes
Add OSM nodes
Don't add OSM ways
Don't add OSM relations
***************************************************
No $HOME found
Testing database connection: test_db
database connection successful: test_db
Connecting to the database
connection success

Dropping tables...
TABLE: ways dropped ... OK.
TABLE: ways_vertices_pgr dropped ... OK.
TABLE: pointsofinterest dropped ... OK.
TABLE: configuration dropped ... OK.
TABLE: osm_nodes dropped ... OK.
TABLE: osm_ways dropped ... OK.
TABLE: osm_relations dropped ... OK.

Creating tables...
TABLE: ways_vertices_pgr created ... OK.
TABLE: ways created ... OK.
TABLE: pointsofinterest created ... OK.
TABLE: configuration created ... OK.
TABLE: osm_nodes created ... OK.
TABLE: osm_ways created ... OK.
TABLE: osm_relations created ... OK.
Opening configuration file: C:\ming64gcc48\projects\osm2pgrouting\rel\osm2pgrouting-pg10-binaries-2.3.1w64gcc48\\share\mapconfig.xml
    Parsing configuration

Exporting configuration ...
  - Done
Counting lines ...
'wc' is not recognized as an internal or external command,

**Comment by robe2** [comment]
works with develop now.  thanks @cvvergara

**Comment by cvvergara** [comment]
@robe2 
Will prepare 2.3.2
