### ISSUE TITLE
Error when importing data.

### ISSUE THREAD

**Issue by rvlander** [pgRouting/osm2pgrouting#204]
Hi have the following error when importing osm data.
```
ERREUR:  relation « configuration » does not exist
LINE 1: ...LECT a.*  FROM  __configuration30445 a LEFT JOIN  configurat...
```
Configuration:
 * Postgres 10
 * Postgis 2.4.2
 * pgrouting 2.5.2
 * osm2pgrouting (compiled from 2.3.2 tag and also from master, using -std=c++14 flag)
 * libpqxx 5.1.0

Data can be fetched using:
```
CITY="Boston_MA"
wget -N --progress=dot:mega \
    "http://download.osgeo.org/livedvd/data/osm/$CITY/$CITY.osm.bz2"
bunzip2 $CITY.osm.bz2
```
I am following the [pgrouting workshop](http://workshop.pgrouting.org/2.4.11/en/chapters/prepare_data.html).

**Comment by cvvergara** [comment]
The workshop uses an old version of osm2pgrouting.
Add the `--clean` flag to your execution, otherwise is expecting to find configuration table
I will tag as a bug, to fix on the next micro release

**Comment by rvlander** [comment]
@cvvergara, it works. Thanks.
