### ISSUE TITLE
End Of File encountered before ways and relations are imported 

### ISSUE THREAD

**Issue by veniversum** [pgRouting/osm2pgrouting#228]
[Here's the osm file](https://gist.github.com/veniversum/11bfc704d802cfd2a094ad7b405ab8a2) that I'm importing.
The config file is just the [default mapconfig.xml](https://github.com/pgRouting/osm2pgrouting/blob/master/mapconfig.xml) provided.
`osm2pgrouting` is built from most recent commit e937efd on master branch.

I'm running with command line options ` --addnodes --attributes --tags`

Only `osm_nodes` gets populated and `osm_ways` and `osm_relations` remain empty even though there are relevant entries in the osm file.
```
Connecting to the database
connection success

.... <bunch of dropping/creating of tables> ....

Opening configuration file: /usr/share/osm2pgrouting/mapconfig.xml
    Parsing configuration

Exporting configuration ...
  - Done
Counting lines ...
  - Done
Opening data file: osm/example.osm      total lines: 23458
    Parsing data

Current osm_nodes:      0
Final osm_nodes:        6223
Current osm_ways:       0
End Of file


    Finish Parsing data

Adding auxiliary tables to database...
... <bunch of other output>
```

Any idea why this is happening?

**Comment by veniversum** [comment]
I seem to have narrowed down the problem. None of the relations matched tags in the config (at least `OSMDocument::AddRelation` was never called), and in combination with the default chunk size of 20000, meant that none of the way data was exported to the database.

I think adding a check for `m_waysPending` in [`OSMDocument::endOfFile()`](https://github.com/pgRouting/osm2pgrouting/blob/56d3385b74be65290e00ac5c653a74ae5001ffb8/src/osm_elements/OSMDocument.cpp#L135) similar to how it's already done in `OSMDocument::AddRelation` suffices as a fix for this bug.

**Comment by cvvergara** [comment]
@cayetanobv 
can we close this issue?

**Comment by cayetanobv** [comment]
Ok, it was fixed.
