### ISSUE TITLE
Command line configuration in print outputs (db password)

### ISSUE THREAD

**Issue by cayetanobv** [pgRouting/osm2pgrouting#234]
Hi team,

I think we could remove db password from command line print outputs because is not a good thing when you have this application in a production environment (... and this output goes to main logs).

Options to solve this issue:
1) We can remove line 101 of prog_options.cpp file: https://github.com/pgRouting/osm2pgrouting/blob/d10845bffd58c2bb78a030d968dd3ee590bcf7d5/src/utilities/prog_options.cpp#L101
2) We can put a flag to show or not show db password.

I would prefer option 1. @cvvergara @dkastl  What do you think about it?

Thanks,

**Comment by dkastl** [comment]
I think your arguments with the password are valid.

**Comment by cayetanobv** [comment]
Ok, thanks, PR merged.
