### ISSUE TITLE
Topology created by osm2pgrouting leaves some ways with identical source and target nodes, making them un-routable

### ISSUE THREAD

**Issue by robhawkes** [pgRouting/osm2pgrouting#24]
After running osm2pgrouting on the Greater London OSM data (listed below) I'm left with a bunch of ways in the ways table that have an identical node id for both the source and target. This makes those ways un-routable, even though the ways seem completely legit and aren't broken in OSM.

The only thing I can think of that may be triggering this bug is that the affected ways are so short (length values in the database of less than 0.00…).

Any ideas? I'd like to see this fixed but in the meantime I'd be happy to settle for a short-term workaround.

Further info
* OSM Data
 * http://download.geofabrik.de/europe/great-britain/england/greater-london.html
* Example way exhibiting issue:
 * GID 420764 (OSM_ID 165256657) in generated ways table
 * SELECT * FROM ways WHERE gid = 420764
* 354 ways with the same issue
 * SELECT * FROM ways WHERE source = target

**Comment by cvvergara** [comment]
With the alpha version this no longer happens
Test on Washington dc area:
```
select gid from ospr.ways where source = target;
 gid 
-----
(0 rows)
```
