### ISSUE TITLE
Incorrect classification of one-ways

### ISSUE THREAD

**Issue by dhshawn** [pgRouting/osm2pgrouting#240]
I used osm2pgrouting to import this **two-way** trunk road: https://www.openstreetmap.org/way/66799462

It doesn't have any direction tags.
![image](https://user-images.githubusercontent.com/41531648/43042355-b0aadede-8d38-11e8-9618-dd4cb7f5f521.png)

After importing using osm2pgrouting it has been flagged as a **one-way**, which seems to be incorrect?

![image](https://user-images.githubusercontent.com/41531648/43042348-7d632b94-8d38-11e8-8b2f-8a470a7abf41.png)

I am a GIS novice; it's possible that there is a simple solution/explanation.

Thanks.

**Comment by dhshawn** [comment]
In the [source code ](https://github.com/pgRouting/osm2pgrouting/blob/91f0163b63837b4f83e1199a1bc53cd46169257c/src/osm_elements/Way.cpp#L206) I see that [highway-trunks](https://wiki.openstreetmap.org/wiki/Tag:highway=trunk) are implied to be one-ways. This is not accurate.

**Comment by cayetanobv** [comment]
Hi @dhshawn ,

According to OSM you are right: https://wiki.openstreetmap.org/wiki/Key:oneway

AFAIK restriction ```oneway=yes``` is only implied in ``` junction=roundabout``` and  ```highway=motorway```. In OSM wiki says "others" but I don't know more cases to apply this restriction. Let me know if you know otrhes applications.

I created this PR to solve this problem: https://github.com/pgRouting/osm2pgrouting/pull/241

Thanks,
