### ISSUE TITLE
osm2pgrouting has issues creating tables

### ISSUE THREAD

**Issue by mhubrich** [pgRouting/osm2pgrouting#243]
Hi all,

I have problems executing `osm2pgrouting`. I get error messages right at the beginning when the tables are created. Here is what I do:

    createdb routing
    psql --dbname routing -c 'CREATE EXTENSION postgis'
    psql --dbname routing -c 'CREATE EXTENSION pgRouting'

Next, I run:

    osm2pgrouting --f Downloads/export.osm --conf osm2pgrouting/mapconfig.xml --dbname routing --username postgres

And get the following output:
```
***************************************************
           COMMAND LINE CONFIGURATION             *
***************************************************
Filename = Downloads/export.osm
Configuration file = osm2pgrouting/mapconfig.xml
host = localhost
port = 5432
dbname = routing
username = postgres
schema= 
prefix = 
suffix = 
Don't drop tables
Don't create indexes
Don't add OSM nodes
***************************************************
Testing database connection: routing
database connection successful: routing
Connecting to the database
connection success
2018-08-02 16:27:14.466 PDT [8474] ERROR:  extension "postgis" already exists
2018-08-02 16:27:14.466 PDT [8474] STATEMENT:  CREATE EXTENSION postgis

Creating tables...
2018-08-02 16:27:14.484 PDT [8477] ERROR:  relation "ways_vertices_pgr" does not exist at character 8
2018-08-02 16:27:14.484 PDT [8477] STATEMENT:  SELECT 'ways_vertices_pgr'::regclass
TABLE: ways_vertices_pgr created ... OK.
2018-08-02 16:27:14.503 PDT [8478] ERROR:  relation "ways" does not exist at character 8
2018-08-02 16:27:14.503 PDT [8478] STATEMENT:  SELECT 'ways'::regclass
TABLE: ways created ... OK.
2018-08-02 16:27:14.511 PDT [8479] ERROR:  relation "pointsofinterest" does not exist at character 8
2018-08-02 16:27:14.511 PDT [8479] STATEMENT:  SELECT 'pointsofinterest'::regclass
TABLE: pointsofinterest created ... OK.
2018-08-02 16:27:14.520 PDT [8480] ERROR:  relation "configuration" does not exist at character 8
2018-08-02 16:27:14.520 PDT [8480] STATEMENT:  SELECT 'configuration'::regclass
TABLE: configuration created ... OK.
Opening configuration file: osm2pgrouting/mapconfig.xml
    Parsing configuration

Exporting configuration ...
  - Done 
    Parsing data

Segmentation fault: 11
```

Does anyone know what's going wrong?

Here some information about my system:

- MacOS 10.13.5
- osm2pgrouting 2.3.6
- pgRouting 2.6.0
- PostgreSQL 10.4
- User `postgres` exists and has superuser role

**Comment by cayetanobv** [comment]
Hi @mhubrich ,

Are you sure your user has permissions? Why don't you supply password?
Are you sure you are using version 2.3.6?

Thanks,

**Comment by mhubrich** [comment]
Hi @cayetanobv,
Thanks for your reply. 

That's the version output I get:

    >> osm2pgrouting --version
    This is osm2pgrouting Version 2.3.6

Here is information about the user:
```
>> psql -U postgres -c "\du"
                                        List of roles
  Role name  |                         Attributes                         | Member of 
-------------+------------------------------------------------------------+-----------
 postgres    | Superuser, Create DB                                       | {}
```

I didn't supply a password because this user doesn't have one. I think there are no problems of this user accessing the database. The output in my initial post says:
```
Testing database connection: routing
database connection successful: routing
Connecting to the database
connection success
```

Tables inside the DB `routing` were even created:
```
>> psql -U postgres -d routing -c "\d"
                    List of relations
 Schema |           Name           |   Type   |  Owner   
--------+--------------------------+----------+----------
 public | configuration            | table    | postgres
 public | configuration_id_seq     | sequence | postgres
 public | geography_columns        | view     | postgres
 public | geometry_columns         | view     | postgres
 public | pointsofinterest         | table    | postgres
 public | pointsofinterest_pid_seq | sequence | postgres
 public | raster_columns           | view     | postgres
 public | raster_overviews         | view     | postgres
 public | spatial_ref_sys          | table    | postgres
 public | ways                     | table    | postgres
 public | ways_gid_seq             | sequence | postgres
 public | ways_vertices_pgr        | table    | postgres
 public | ways_vertices_pgr_id_seq | sequence | postgres
```
However, all tables are empty (except of `configuration`).

**Comment by cayetanobv** [comment]
Ok, thanks. It seems is a dataset issue. Could you upload your osm dataset to test it?

**Comment by mhubrich** [comment]
Thanks a lot! Here is the file I used:
[export.osm.zip](https://github.com/pgRouting/osm2pgrouting/files/2258139/export.osm.zip)
I didn't find any detailed information on how the osm file should look like. I used [Overpass-Turbo](http://overpass-turbo.eu/) to create the file.

Do you have an example file for me I could try on my machine?

**Comment by cayetanobv** [comment]
Hi @mhubrich ,

I tried to use your dataset but I see very strange issues in your geometries. You can see this screenshot from QGIS of your OSM dataset:
![image](https://user-images.githubusercontent.com/7315379/43687964-dc62abd0-98df-11e8-9880-f1d6c83ea901.png)

I downloaded your area and it is working fine with osm2pgrouting (screenshot of OSM dataset):
![image](https://user-images.githubusercontent.com/7315379/43687962-cf77755e-98df-11e8-825d-8ff38762165f.png)

I think there are something strange in your downloaded dataset. You can try to download with another tools:

- QGIS: you can use OSMDownloader plugin.
- You can use Overpass API in your shell. Examples: https://github.com/pgRouting/osm2pgrouting/blob/master/tools/data/getdata.sh

Thanks,

**Comment by mhubrich** [comment]
Thank you so much, @cayetanobv. That explains a lot!

You were a good help here, thanks for your time :)

**Comment by cayetanobv** [comment]
Thanks to you @mhubrich !
