### ISSUE TITLE
How to get tags such as surface, lanes from ways via pgrouting.

### ISSUE THREAD

**Issue by Ravitiwari0412** [pgRouting/osm2pgrouting#264]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample Data**
If applicable, add sample data to help explain your problem.

**Specifications (please complete the following information):**
Use the commands:
```
SELECT version();
SELECT postgis_full_version();
SELECT pgr_version();
```

**Additional context**

**Comment by dkastl** [comment]
You labeled this a bug. What is the bug?

**Comment by Ravitiwari0412** [comment]
Hi Daniel,
Thanks for replying. Actually I was using osm and pgrouting, from last 1
month. And was having difficulty finding tags other than specified in ways.
Also, I haven't raised any issue on github so didnt know how to change
label to normal query, instead of bug.I know now --addnodes gives me all
tags. You can close this or I will tomorrow.
Thanks for your help

**Comment by dkastl** [comment]
Ah, I see. If this is a question, then the better place to ask is https://gis.stackexchange.com/

**Comment by Ravitiwari0412** [comment]
Sure, but I dont think people reply there this fast :) .
