### ISSUE TITLE
Ways table with empty Source, Target and Cost.

### ISSUE THREAD

**Issue by AnderPijoan** [pgRouting/osm2pgrouting#28]
Hi,

I am using osm2pgsql and when finishing these three columns are empty in the ways table. It generates geometries, tables and everything but doesn't fill source, target and cost values. Here's the execution:

```
Split ways
Dropping tables...
Creating tables...
NOTICE:  CREATE TABLE / PRIMARY KEY creará el índice implícito «nodes_pkey» para la tabla «nodes»
Nodes table created
2create ways failed: 
NOTICE:  CREATE TABLE / PRIMARY KEY creará el índice implícito «types_pkey» para la tabla «types»
Types table created
Way_tag table created
Relations table created
Relation_ways table created
NOTICE:  CREATE TABLE / PRIMARY KEY creará el índice implícito «classes_pkey» para la tabla «classes»
Classes table created
Adding tag types and classes to database...
Adding relations to database...
Adding nodes to database...
Adding ways to database...
Creating topology...
NOTICE:  PROCESSING:
NOTICE:  pgr_createTopology('ways',1e-05,'the_geom','gid','source','target','true')
NOTICE:  Performing checks, pelase wait .....
NOTICE:  -------> ways not found
Create Topology success
#########################
size of streets: 123588
size of splitted ways : 271734
finished
```

In **Export2DB::createTables** the query " SELECT AddGeometryColumn('" + tables_prefix + "ways','the_geom',4326,'LINESTRING',2);" is returning a 2 so the execution says that "create ways failed" although having done it.

In **Export2DB::exportWays** I see that each way is inserted in the database but source, target and to_cost fields not inserted. Why aren't these inserted?

Finally I don't know where the **NOTICE:  -------> ways not found** error is coming from and what it means. Maybe here is where the missing values are filled and it is not able to find the table?

Thank you very much.

**Comment by cvvergara** [comment]
With the alpha version this no longer happens
Test on Washington dc area:
```
select gid from ospr.ways where source is NULL or target is NULL or cost is NULL;
 gid 
-----
(0 rows)
```
