### ISSUE TITLE
Issue with data import: fe_sendauth: no password supplied 

### ISSUE THREAD

**Issue by curiousaboutgis** [pgRouting/osm2pgrouting#283]
Hello! I am trying to start osm2pgrouting by loading osm data into it, but I get the following error message:

osm2pgrouting --f your-OSM-XML-File.osm --conf mapconfig.xml --dbname routing --username postgres --clean

Execution starts at: Tue Jul 14 15:40:48 2020
`       COMMAND LINE CONFIGURATION             *
Filename = your-OSM-XML-File.osm
Configuration file = mapconfig.xml
host = localhost
port = 5432
dbname = routing
username = postgres
schema=
prefix =
suffix =
Drop tables
Don't create indexes
Don't add OSM nodes

Testing database connection: routing
fe_sendauth: no password supplied
`
This is postgres issue apparently, how could I supply it with password?

**Comment by cayetanobv** [comment]
Hi @curiousaboutgis . You need to add `-W` argument with your password.

**Comment by curiousaboutgis** [comment]
> Hi @curiousaboutgis . You need to add `-W` argument with your password.
Omg thanks God, it worked. I mean I tried before, but my password for postgres contained symbols like !,1234,  and it was written as  !,1234, event not recognized. 

But now it worked thanks god!

**Comment by curiousaboutgis** [comment]
the whole command should look like: 
osm2pgrouting --f your-OSM-XML-File.osm --conf mapconfig.xml --dbname routing --username postgres -W yourpassword --clean
