### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devrimgunduz** [pgRouting/osm2pgrouting#286]
Hi,

It's been more than 2 years since last release, and I'm seeing lots of commits since then. Any plans for a new release? I am looking for updating osm2pgrouting RPMs in the PostgreSQL official RPM repo.

Regards, Devrim

**Comment by dkastl** [comment]
Thank you, Devrim! That's a good question.

@cayetanobv @cvvergara , what do you think?

**Comment by cayetanobv** [comment]
There aren't so many new things but we can release 2.3.7 version to include the last fixes. I can take care of that. Thanks @devrimgunduz

**Comment by cayetanobv** [comment]
@dkastl @cvvergara 
I've updated NEW file for the new release: https://github.com/pgRouting/osm2pgrouting/pull/288
After the merge, I will create the new release in Github.

**Comment by cayetanobv** [comment]
A new release was created:
https://github.com/pgRouting/osm2pgrouting/releases/tag/v2.3.7
