### ISSUE TITLE
2.3.7 compile error

### ISSUE THREAD

**Issue by devrimgunduz** [pgRouting/osm2pgrouting#289]
[osm2pgrouting-2.3.7-builderror.txt](https://github.com/pgRouting/osm2pgrouting/files/5907335/osm2pgrouting-2.3.7-builderror.txt)

Hi,

Cannot build 2.3.7 on Fedora (GCC 10.2.1 + libpqxx 7.2.0 and 7.3.1) and RHEL 8 (GCC 8.3.1 + libpqxx 7.2.0 ). Errors are attached.

Not sure this is related, but on Fedora I get:

```
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (PQXX) does
  not match the name of the calling package (LibPQXX).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindLibPQXX.cmake:37 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:14 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
``` 

...though this message does not appear on RHEL 8.

Any ideas how to fix?

Regards, Devrim

**Comment by cayetanobv** [comment]
Hi @devrimgunduz , these errors from compiler are because Libpqxx v7.1 require C++17.

**Comment by cayetanobv** [comment]
This is not a bug. It's an improvement so I'm going to change the tag.

**Comment by devrimgunduz-edb** [comment]
Any updates on this?

**Comment by cvvergara** [comment]
@devrimgunduz 
I will work on this next week.
Sorry for the delay.

**Comment by cvvergara** [comment]
@devrimgunduz 
Sorry for the delay, the PR is ready if you can review #292 
The most critical part is the change on the [minimum standard for C++]( https://github.com/pgRouting/osm2pgrouting/blob/36b304ad66c9083e8a5e183f4e1204e10609c4e7/CMakeLists.txt#L41)
* C++ minimum standard depends on libpqxx
  * For version libpqxx 6: C++14
  * For version libpqxx 7: C++17 see [here](https://github.com/jtv/libpqxx#upgrade-notes)

I also modified FindPQXX that detects the version, can you verify that it works as it should on centos.
