### ISSUE TITLE
importing osm reports "unknown maxspeed value: xx mph"

### ISSUE THREAD

**Issue by duongnt** [pgRouting/osm2pgrouting#29]

**Comment by sarthak-0415** [comment]
@openbrian 
we are working on modifying osm2pgrouting and I would like to have your changes,
can you make the merge agoinst gsoc-develop please.
Sarthak

**Comment by openbrian** [comment]
Yes, I'll try to work on this soon.
Brian
http://derocher.org/~brian
http://mappingdc.org

**Comment by jmarca** [comment]
for what it's worth, I did a super quick merge of openbrian's master with the gsoc-develop branch and it seemed to merge cleanly (no conflicts at least).  I'm going to try to compile, install, and run against California.osm next

**Comment by openbrian** [comment]
Cool!

**Comment by cvvergara** [comment]
Thanks, I also merged on merge-dev-gsoc-cleanup
which now has latest changes.
Its compiling, running takes less time.
right now I there is a script that searches for the osm files under tools/data
and in tools/data there is a script that gets the data

for the moment I am running the script twice with small.osm
just to check that data dosn't get duplicated after the second try.
(which in vertices table does get duplicated, but I am working on it)
You might want to try that one also

**Comment by jmarca** [comment]
Had some trouble running with the latest additions, but at least the MPH stuff is working fine for me.  I checked out a branch starting with 84d32084c52df5d5ceeaded5b396767bf1fcd017 (Merge pull request #37 ...) and it ran fine on California.osm.  The as-of-yesterday-morning master branch wouldn't run for me---the full stop was some NULL problem I didn't understand---but those issues aren't relevant to this one.

**Comment by cvvergara** [comment]
@jmarca 
I am working on the code. The master branch is somehow broken. It can not bet changed until an official release comes out.

**Comment by cvvergara** [comment]
Fixed on 2.1 alpha
