### ISSUE TITLE
Some way are not imported in the ways table

### ISSUE THREAD

**Issue by TANK2003** [pgRouting/osm2pgrouting#296]
**Problem**
This way in METZ is not imported in the way table : https://www.openstreetmap.org/way/688415790#map=19/49.11324/6.18126
I have import the mapconfig.xml configuration. 2.3.8

**Platform/versions**
Debian buster, osm2pgrouting V 2.3.8

SELECT version() => postgres 13.3
SELECT postgis_full_version(); => Postgis 3.1.2
SELECT pgr_version(); => 3.2.0

**Comment by ImreSamu** [comment]
imho: 
try with bigger chunk size ( `--chunk 10000000` ) in some cases the default is not enough
see https://github.com/pgRouting/osm2pgrouting/issues/237#issuecomment-406221767

**Comment by TANK2003** [comment]
it works ! Thank you very much
