### ISSUE TITLE
Unable to create 'ways' topology

### ISSUE THREAD

**Issue by AritzBi** [pgRouting/osm2pgrouting#30]
Hi!

I am kind a noob in all this geospatial stuff, but I have been trying to do this:

```
osm2pgrouting -dbname mydb -user myuser -passwd mypass -conf mapconfig.xml -file bilbao.osm 
```

But when it is executed I get the following error:

```
Create index add on source failed: ERROR:  relation "source_idx" already exists

Create index add on target failed: ERROR:  relation "target_idx" already exists

Create geom index on ways failed: ERROR:  relation "geom_idx" already exists

Create unique index on ways failed: ERROR:  relation "ways_gid_idx" already exists

Create Topology failed: ERROR:  function pgr_createtopology(unknown, numeric, unknown, unknown) does not exist
LINE 1: SELECT pgr_createTopology('ways', 0.00001, 'the_geom', 'gid'...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Looks like that it can't create the new topology.

Any help would be appreciated!

Thanks in advance!

**Comment by JasonID** [comment]
hi AritzBi ,i have the same error like you ,and "create extension pgrouting" shows "CREATE EXTENSION" ,it shows sucessfully.and the funciton pgr_createTopology existed,but the table of "ways"doesn't exist,please help me ,thank you very very much!
