### ISSUE TITLE
Error during topology creation

### ISSUE THREAD

**Issue by MarHoff** [pgRouting/osm2pgrouting#32]
Hello, 

I just installed a brand new Ubuntu server 14.04 LTS (Thursty).
Installing the pakages via apt-get (postgres, postgis and pgrouting from instable PPA) worked like a charm.

However I'm fronting a strange error while trying to load data from an OSM xml.
Everything run fine until the "create topology" step.
```
$ osm2pgrouting -file "20140429_highways_overpass.osm" 
 -conf "/usr/share/osm2pgrouting/mapconfig.xml"   
 -dbname bd_routing  
  -user                     admin       
   -passwd xxxxxxx     
    -clean

(...)

Creating topology...
NOTICE:  PROCESSING:
NOTICE:  pgr_createTopology('ways',1e-05,'the_geom','gid','source','target','tru                    e')
NOTICE:  Performing checks, pelase wait .....
NOTICE:  -------> ways not found
Create Topology success

(...)
```
Please notice I don't run the command as postgres user, this is by design as our policy is to 'SET ROLE to postgres' once logged-in with 'admin' when superuser right are needed.

I managed to succesfully create the topology afterward using this command in PgAdminIII:
```
SELECT pgr_createTopology('ways',1e-05,'the_geom','gid','source','target','true')
```
So this might indicate that it just a wrong escaping problem when the command is run by osm2pgrouting so this could be fixed quite easily.

Don't hesitate to ask for more details (and sorry for my english, I'm french ;)
Best regards

Martin Hoffmann

### Configuration:
Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)
PostgreSQL 9.3.4 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-16ubuntu6) 4.8.2, 64-bit
Postgis 2.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
PgRouting v2.0.0 (build 3) master (boost 1.54.0)

### OSM Overpass query (pretty huge 326Mo) :
(provided for information only as this don't seems to be the problem)
```
`<osm-script>
  <osm-script output="xml">
	<!-- Selectionner toutes les relation de routes dans l'emprise-->
    <query into="cr" type="relation">
      <bbox-query e="7.823638916015625" into="_" n="48.372672242291294" s="47.39463076190644" w="6.686553955078124"/>
      <has-kv k="highway"/>
    </query>
	<!-- Selectionner toutes les way de routes dans l'emprise-->
    <query into="cw" type="way">
      <bbox-query e="7.823638916015625" into="_" n="48.372672242291294" s="47.39463076190644" w="6.686553955078124"/>
      <has-kv k="highway"/>
    </query>
	<!-- Réaliser une union des deux séléction et inclure tous les élément enfants-->
    <union>
      <item set="cr"/>
      <recurse from="cr" type="down"/>
      <item set="cw"/>
      <recurse from="cw" type="down"/>
    </union>
    <print mode="meta" order="quadtile"/>
  </osm-script>
</osm-script>
```

**Comment by robe2** [comment]
The pgr_CreateTopology is no longer used for osm2pgrouting 2.1+.  The newer version uses the implicit osm topology.  Also it is now possible to load piecemeal multiple osm files, so using CreateTopology when loading multiple files doesn't work well.
