### ISSUE TITLE
import issue - costs not set, but reverse costs are

### ISSUE THREAD

**Issue by Styp** [pgRouting/osm2pgrouting#33]
I noticed a strange error during the osm2pgrouting import. Right now I use a ppa repository as my installation source. Unfortunatly I can no tell the exact version..., but should be in the 2.0.x. I run pgrouting 2.0.1 final.

It seems that the import clears quite well.
![image](https://cloud.githubusercontent.com/assets/1202069/3026539/a693143a-e016-11e3-97b3-229d461e7fac.png)

But costs columns are empty...
![image](https://cloud.githubusercontent.com/assets/1202069/3026591/7e435192-e017-11e3-8162-cb2232abf586.png)

Is this really a new bug? Or do I need to patch the piece of software?

**Comment by rleh** [comment]
Same here with the current git master (8c5f5e8) on Fedora.

**Comment by cvvergara** [comment]
We are redesigning osm2Pgrouting, I will mark it as bug report, and we will make tests on the new design to make sure that doesn't happen.

**Comment by cvvergara** [comment]
I reproduced the error on the current code:
select gid from ways where not to_cost is NULL;
 gid 
-----
(0 rows)

**Comment by cvvergara** [comment]
On develop branch or in [V2.1 alpha](https://github.com/pgRouting/osm2pgrouting/releases/tag/osm2pgrouting-2.1.0-alpha) Or in the near future V.1
