### ISSUE TITLE
Osm data to be used while developing

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osm2pgrouting#44]
I would like to use the area that workshop use. Mainly because workshop is based on that information, and the integrity of the workshop should remain intact.
Incremental insertions can be tested by inserting smaller bounding boxes of the workshop data.

@dkastl 
The bounding box defined here:
http://workshop.pgrouting.org/chapters/installation.html#data
Doesn't correspond to the data that has the pgrouting-workshop repository when using:
sudo apt-get install pgrouting-workshop

**Comment by dkastl** [comment]
The workshop data usually gets updated with every FOSS4G. So next time I t should be Seoul.

**Comment by cvvergara** [comment]
So, for the moment, for short/fast file to be processed, lets use
BBOX="-122.8,45.4,-122.5,45.6"
wget --progress=dot:mega -O "sampledata.osm" "http://www.overpass-api.de/api/xapi?*[bbox=${BBOX}][@meta]"
But lets think of it like if it is all Europe, that is, process it like if it was a big file, that way when we test on a big file like Germany or a mounster file like Europe the transition is smooth.

**Comment by cvvergara** [comment]
I will close this issue as it was used for GSoC developing 2 years ago
