### ISSUE TITLE
ProgramOptions: --prefixtables <prefix> / -- sufix < suffix>

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osm2pgrouting#52]
`-prefixtables <prefix> `
 specifics: optional (default value???)
In the help suggest  meaningfull prefixes eu_ or mx_ 
and its a pŕefix to `ways` 
Component of issue: #43

`--prefix` instead of `--prefixtables`

Some Q's:
if "multimodal" then tables can have also a predefined suffix?
mx_ways_bus
mx_ways_train
etc.
or multimodal can fit on the same table with an extra column that indicates which kind of transportation???
if the user only wants to do train routing, can it be compulsory _train??, or can he choose??
if he can choose the we also need `--sufix`
The `--help` should be clear on what we decide.

**Comment by cvvergara** [comment]
Related problem Issue #39

**Comment by cvvergara** [comment]
@dkastl 
prefix or prefixtables?
prefixtables is what is current.

**Comment by dkastl** [comment]
I would use `--prefix` because it's shorter.
Is there anything else that could be used for `--prefix` than for tables?

**Comment by cvvergara** [comment]
no that I know of.
(correct me if I am wrong) right now length is given in degrees distance also cost & reverse cost.

But I also want the suffix
so a table can go like: (thinking for the future)
eu_ways_sec   //  sec as in time to traverse the edge in cost & reverse_cost
eu_ways_mts   // mts as in meters (the length column filled with meters)

which by the way remind me, in all the documentation of pgRouting edge_table is used instead of ways which is what osm2pgrouting uses.
