### ISSUE TITLE
Make sure osm bigint id information is properly handled in the code

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osm2pgrouting#60]
@aj07mm mentions in #59  about a value that is too large for an int, the code might be trying to store those values on an int4 and not on a int8. 
This error might be independent of the architecture,  but needs to be verified.

**Comment by sanak** [comment]
The following mainstream fix may be related with this.
https://github.com/pgRouting/osm2pgrouting/commit/7b017c7ca33bb62369b4ba354a723267372d6a96

**Comment by cvvergara** [comment]
The fix talks about 32bit-systems, so probably on the c/c++ code the use int64_t should be enforced, that is because its a fact that osm uses big int ID's for the geometries,  not many operations are done with ID, except like for comparing, so for 32bit systems an overhead might be created by the compiler.
http://stackoverflow.com/questions/5530906/do-i-need-to-have-64-bit-processor-to-use-64-bit-data-type.

**Comment by cvvergara** [comment]
I found he following in OSM wiki:
http://wiki.openstreetmap.org/wiki/64-bit_Identifiers
and there is a link about it:
http://lists.osgeo.org/pipermail/pgrouting-users/2013-March/001400.html
