### ISSUE TITLE
Cost column in not populated

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osm2pgrouting#62]
Using this file 
http://imaptools.com:8080/dl/Sion.zip
 from https://github.com/pgRouting/pgrouting/issues/278 
```
osm2pgrouting -file "Sion.osm"   \
                       -conf "/usr/share/osm2pgrouting/mapconfig.xml"   \
                      -user myuser
                      -dbname issue278
                      -host localhost
                     -clean

psql issue278

select count(*) from ways where  to_cost is NULL;
 count 
-------
 20399

select count(*) from ways where not to_cost is NULL;
 count 
-------
     0
```

**Comment by sarthak-0415** [comment]
1) to_cost column name should be "cost"
because "cost" is the name that pgRouting use for that column and we need to be consistent

2) we need to fill it up.
because "cost" is compulsory to have values in the queries of pgRouting

**Comment by cvvergara** [comment]
@sarthak-0415 
thanks for noticing it,
can you work on this errors before other changes, that way we can merge it into develop and have those bugs fixed
please.

**Comment by cvvergara** [comment]
@sarthak-0415 
Thanks for noticing it,
please can you fix this bugs, so we can merge it into develop.
