### ISSUE TITLE
Set a target schema in stack exchange

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osm2pgrouting#75]
[post by mapBaker](http://gis.stackexchange.com/questions/154881/how-to-set-the-target-schema-using-osm2pgrouting)
Is it possible to set the target database schema using osm2pgrouting?
After some debate and troubleshooting, I've decided to host my OSM-based pgRouting data in the same database as the rest of my data, but want to use a different schema (one big issue was using dblink, which I can't get to work anyway).
However, osm2pgrouting doesn't expose the ability to specify the target schema.

**Comment by cvvergara** [comment]
@sarthak-0415 
this is related to #43 what would be an appropriate flag for this?

**Comment by robe2** [comment]
I'm closing this since its' not in osm2pgrouting 2.1.0beta and develop branches
